version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "household-budget-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x1u8zcw04bvr"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = true